name = "ostree-demo"

description = ""
version = "0.0.3"
modules = []
groups = []


# MicroShift and dependencies

[[packages]]
name = "microshift"
version = "*"

[[packages]]
name = "microshift-containers"
version = "*"

[[packages]]
name = "microshift-hello-world"
version = "*"

[[packages]]
name = "microshift-hello-world-manifests"
version = "*"

[[packages]]
name = "openshift-clients"
version = "*"


# troubleshooting tools

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"


# other

[[packages]]
name = "redhat-release"
version = "*"


# customizations

[customizations]

[customizations.services]
enabled = ["crio", "microshift"]
